title: UNITN Fisica Orale
description: Raccolta delle domande dell'orale in ordine tematico per il corso di fisica 1 del Prof. Iuppa.
baseurl: "/UNITN-fisica-orale" 
url: "https://federicomenegoz.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_TeX: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

mathjax: true

exclude:
  - README.md
