# _config.yml
title: Your Math Site
description: A site with mathematical content
baseurl: "" # for user sites, leave empty; for project sites use "/repo-name"
url: "https://your-username.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_TeX: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Enable math rendering
mathjax: true